package Git;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MyAdmin
 */
public class JFLogin extends javax.swing.JFrame {
public String empno;
public String IP;
public static String IPall;
    /**
     * Creates new form MYJFrame
     */
    public JFLogin() throws UnknownHostException, SocketException {
        
        
        try {
            this.objSettings = new getSettings();
            objSettings.LoginWindow=this;
        } catch (IOException ex) {
            Logger.getLogger(JFLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        IP = InetAddress.getLocalHost().getHostAddress();
                 
                  //  ListNets IP = new ListNets();
    }
    private getSettings objSettings;
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmpno = new javax.swing.JTextField();
        lblResponse = new javax.swing.JLabel();
        cmdLogin = new javax.swing.JButton();
        lblLockImg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lakshmi machines works");
        setBackground(new java.awt.Color(33, 60, 137));
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 60, 137));
        jLabel1.setText("Employee No.");

        txtEmpno.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtEmpno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpnoActionPerformed(evt);
            }
        });
        txtEmpno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpnoKeyPressed(evt);
            }
        });

        lblResponse.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblResponse.setForeground(new java.awt.Color(204, 0, 0));
        lblResponse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        cmdLogin.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cmdLogin.setForeground(new java.awt.Color(33, 60, 137));
        cmdLogin.setText("Login");
        cmdLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdLoginMouseClicked(evt);
            }
        });
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ver. 2.09");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(txtEmpno, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLockImg, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmpno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cmdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLockImg, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(380, 380, 470, 0);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 60, 137));
        jLabel3.setText("Employee No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 30, 840, 100);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 60, 137));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 1440, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdLoginMouseClicked
        // TODO add your handling code here:
LoginSubmit();
        
    }//GEN-LAST:event_cmdLoginMouseClicked
private void LoginSubmit() 
{                                  
    try {
       //  IP = InetAddress.getLocalHost().getHostAddress();
        // jTextField1.setText(IP);
        //    System.out.println(InetAddress.getLocalHost().getHostAddress());
            String sTmp = objSettings.callURL(objSettings.URLEMPVALIDATE.replaceAll("#empno#", txtEmpno.getText()));
            System.out.println(sTmp);
        if(sTmp.indexOf(objSettings.RecordSep)<0)
        {
            lblResponse.setText("Invalid Employee Number");
            txtEmpno.selectAll();
            return;
        }
        objSettings.empno = txtEmpno.getText();
        //getSettings.empno = txtEmpno.getText();
        
                //sTmp.split(RecordSep);
        this.lblResponse.setText("Success" );
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(JFLogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(JFLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
          
          
            }});
        this.dispose();
        //this.dispose();
        objSettings.LoginWindow=this;
        //this.setVisible(false);
        //this.dispose();

            } catch (Exception e) 
            {
          this.lblResponse.setText("Unable to connect the server" );      
    }

}
public void ClearTextBox()
{
    txtEmpno.setText("");
    lblResponse.setText("");
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        this.setExtendedState(this.MAXIMIZED_BOTH);
        //new File(".").getAbsolutePath().
        ImageIcon img1 = new ImageIcon(objSettings.AppImagePath+ "lock.png");
               // img1.getImage().getGraphics()
        lblLockImg.setIcon(img1);
        //lblLogoImg.setIcon(new ImageIcon(objSettings.AppImagePath+ "logo.jpg"));
        //lblLogoImg.setAlignmentX((float)0.5);
        //lblLogoImg.setAlignmentY((float)0.5);
        //this.getContentPane().setBackground(new Color(255,255,234));
        
//        lblLogoImg
        
        
        /*JLabel background = new JLabel(new ImageIcon(objSettings.AppImagePath+ "Backimg.jpg"));
background.setLayout( new BorderLayout() );
//background.setLayout( new  );        

//this.setContentPane( background );
background.setOpaque(true);
        cmdLogin.setIcon(new ImageIcon(objSettings.AppImagePath+ "keybutton.jpg"));
        this.getContentPane().setLayout(new FlowLayout());
        //this.getContentPane().add(lblLogoImg)
        */
                
        //System.out.println(objSettings.AppImagePath+ "logo.jpg");

        
        /*DropShadow shadow = new DropShadow();
        
        shadow.setColor(Color.BLACK);
        shadow.setOffsetX(0);
        shadow.setOffsetY(5);*/
        //shadow.setShowBottomShadow(true);
        //shadow.setShowTopShadow(true);
        //this.setBorder(shadow);
        

        
        //jPanel1.setAlignmentX((float) (this.getMaximizedBounds().getWidth()/2));
        //jPanel1.setAlignmentY(CENTER_ALIGNMENT);
    }//GEN-LAST:event_formWindowOpened

    private void txtEmpnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpnoKeyPressed
        // TODO add your handling code here:
        System.out.println(evt.getKeyChar() + " " +evt.getKeyCode());
        if(evt.getKeyCode() == 10) {
      // Enter was pressed. Your code goes here.
            LoginSubmit();
   }
        
    }//GEN-LAST:event_txtEmpnoKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowActivated

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void txtEmpnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      
    //SomeWatchFile someWatchFile = new SomeWatchFile("HELLO.txt"); 
     //   System.out.println(someWatchFile);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new JFLogin().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(JFLogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SocketException ex) {
                    Logger.getLogger(JFLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                System.out.println("Start Main"); //Joswa
                
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLockImg;
    private javax.swing.JLabel lblResponse;
    private javax.swing.JTextField txtEmpno;
    // End of variables declaration//GEN-END:variables
}
